
langs("Python")

py_library(
  name = "html",
  srcs = [ "html.py" ],
  deps = [ "//impulse/util:typecheck" ],
)

py_library(
  name = "tables",
  srcs = [ "tables.py" ],
  deps = [
    ":html",
    "//impulse/util:typecheck"
  ],
)